### ISSUE TITLE
CSS绘制常见的图形

### ISSUE THREAD

**Issue by metroluffy** [metroluffy/interview-prepare#19]
利用border相关属性。

## 三角形

```css
.triangle {
    width: 0;
    height: 0;
    border-right: 50px solid transparent;
    border-top: 50px solid blue;
    border-left: 50px solid transparent;
}
```

## 梯形

```css
.trapezoid {
  width:100px;
  height:0;
  border-right: 50px solid transparent;
  border-bottom: 50px solid blue;
  border-left: 50px solid transparent;
}
```

## 扇形
其实就是三角形加了一个`border-radius:50%`
```css
.sector {
    width: 0;
    height: 0;
    border-right: 50px solid transparent;
    border-top: 50px solid blue;
    border-left: 50px solid transparent;
    border-radius: 50%;
}
```

## 箭头

如代码，就是两个三角形叠起来，再用定位做个offset（控制线的粗细），方向还是border相关属性控制的。

```css
.arrow{
    position:relative;
}
/*黑色三角形   */
.arrow:before{
    content: "";
    display: block;
    position: absolute;
    top: 50%;
    right: 0;
    width: 0;
    height: 0;
    border:10px solid;
    border-color: transparent transparent transparent #000;
}
/*背景色三角形*/
.arrow:after{
    content: "";
    display: block;
    position: absolute;
    top: 50%;
    right: 1px;
    width: 0;
    height: 0;
    border:10px solid;
    border-color: transparent transparent transparent #fff;
}
```

## 椭圆

```css
.oval {
    width: 200px;
    height: 100px;
    background: red;
    -moz-border-radius: 100px / 50px;
    -webkit-border-radius: 100px / 50px;
    border-radius: 100px / 50px;
}
```
